# config.yaml
# Configurações da aplicação para fácil ajuste sem alterar o código.

# Limites de processamento de arquivos
file_limits:
  max_file_size_mb: 200
  # Limite de linhas para ativar a amostragem automática em datasets grandes
  sampling_threshold_rows: 100000
  # Número de linhas a serem usadas na amostragem
  sampling_rows: 50000

# Configurações de análise
analysis:
  # Número de queries sugeridas na pré-análise
  num_suggested_queries: 5

# Configurações do LLM (Gemini)
llm:
  # Modelo a ser usado. 'gemini-1.5-flash' é rápido e econômico.
  model_name: "gemini-1.5-flash"
  # Parâmetros de geração
  temperature: 0.0
  max_output_tokens: 2048

# Configurações da interface
ui:
  app_title: "ARCHITECT-X: Agente EDA com Gemini"
  sidebar_header: "Configurações"